gui:
  branchColorPatterns:
    '^conflicts/': '#e78284'
    '^hotfix/': '#ea999c'
    '^feature/': '#7dc4e4'
    '^bugfix/': '#e5c890'
    '^chore/': '#8caaee'
    '^release/': '#a6da95'
  theme:
    activeBorderColor:
      - '#ef9f76'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#ef9f76'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'

  authorColors:
    '*': '#babbf1'
  # showFileTree: false
  switchTabsWithPanelJumpKeys: true
git:
  autoForwardBranches: none
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: o
    context: 'localBranches'
    command: 'gh pr view --web {{.SelectedLocalBranch.Name }}'
    description: 'Open PR for selected branch (web)'
    loadingText: "Opening pr in browser..."
  - key: O
    command: "gh pr create --fill --web --base {{.Form.Branch}} --label {{.Form.Label}}"
    context: 'localBranches'
    description: "Create pull request on Github (web)"
    loadingText: "Creating pull reques on Github..."
    prompts:
      - type: "input"
        title: "Choose BASE branch"
        key: "Branch"
        suggestions:
          preset: 'branches'
      - type: 'input'
        title: 'Choose label'
        key: 'Label'
        initialValue: "feature"
        suggestions:
          command: "gh label list --json name --jq '.[].name'"
  - key: <c-g>
    description: "Github pull requests"
    commandMenu:
      - key: n
        command: "gh pr create --fill --web --base {{.Form.Branch}} --label {{.Form.Label}}"
        context: "global"
        description: "Create pull request on Github (web)"
        loadingText: "Creating pull reques on Github..."
        prompts:
          - type: "input"
            title: "Choose BASE branch"
            key: "Branch"
            suggestions:
              preset: 'branches'
          - type: 'input'
            title: 'Choose label'
            key: 'Label'
            initialValue: "feature"
            suggestions:
              command: "gh label list --json name --jq '.[].name'"
      - key: o
        context: 'localBranches'
        command: 'gh pr view --web {{.SelectedLocalBranch.Name }}'
        description: 'Open PR for selected branch (web)'
      - key: l
        command: "gh dash"
        context: "global"
        output: "terminal"
        description: "View pull requests (gh-dash)"
  - key: X
    description: "Various commands"
    commandMenu:
      - key: p
        command: "git fetch -p"
        context: "global"
        description: "Fetch (and prune)"
        loadingText: "Fetching"
        prompts:
          - type: "confirm"
            title: "Fetch and Prune?"
            body: "Are you sure?"
