gui:
  branchColorPatterns:
    '^conflicts/': '#e78284'
    '^hotfix/': '#ea999c'
    '^feature/': '#a6d189'
    '^bugfix/': '#e5c890'
    '^chore/': '#8caaee'
  theme:
    activeBorderColor:
      - '#ef9f76'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#ef9f76'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'

  authorColors:
    '*': '#babbf1'
  # showFileTree: false
  switchTabsWithPanelJumpKeys: true
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
# git:
#   paging:
#     colorArg: always
#     pager: delta --dark --paging=never
