format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = """
$cmd_duration\
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
# vicmd_symbol = "[\\[N\\]](bold yellow)"
vicmd_symbol = "[N](bold yellow)"

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = true

[cmd_duration]
min_time = 3000
format = "[$duration]($style)"
style = "bold yellow"
show_milliseconds = false

[git_branch]
format = "[$branch]($style)"
style = "dimmed"

[git_status]
format = "([$modified $ahead_behind $conflicted]($style))"
style = "cyan"
conflicted = '[CONFLICTED](bold red)'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
modified = '[*](dimmed)'
staged = "+"
renamed = "»"
deleted = "✘"

