# Homebrew aliases
alias brup='brew update && brew upgrade'
alias brout='brew outdated'
alias bri='brew install'
alias bru='brew uninstall'
alias brl='brew list'
alias brs='brew search'
alias brin='brew info'
alias brdr='brew doctor'
alias brse='brew services'
