require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.cpu")
require("items.widgets.ram")
require("items.widgets.docker")
require("items.widgets.wifi")
require("items.widgets.github")
require("items.widgets.linear")
