[manager]
append_keymap = [
    { on = [ "g", "q" ],       run = "cd ~/dotfiles",                   desc = "Goto dotfiles" },
    { on = [ "g", "?" ],       run = "help",                            desc = "View help" },
    { on = "<C-p>",            run = ''' shell 'qlmanage -p "$@"' ''',  desc = "Preview" },
]
